### ISSUE TITLE
Azure pipeline docker image not found

### ISSUE THREAD

**Issue by snazy2000** [CrowdStrike/container-image-scan#54]
We are trying to use the image scan inside azure pipelines based off the the examples in https://github.com/CrowdStrike/image-scan-example

When it comes to trying to get the image locally we get the following error

```
2022-09-28T11:57:18.4261750Z ##[section]Starting: Scan container-image
2022-09-28T11:57:18.4268475Z ==============================================================================
2022-09-28T11:57:18.4268813Z Task         : Command line
2022-09-28T11:57:18.4269170Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-09-28T11:57:18.4269498Z Version      : 2.201.1
2022-09-28T11:57:18.4269728Z Author       : Microsoft Corporation
2022-09-28T11:57:18.4270099Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-09-28T11:57:18.4270522Z ==============================================================================
2022-09-28T11:57:18.5540733Z Generating script.
2022-09-28T11:57:18.5549051Z ========================== Starting Command Output ===========================
2022-09-28T11:57:18.5571342Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/18582713-5b44-4d90-b142-d7bde8b94fc6.sh
2022-09-28T11:57:20.7445712Z Defaulting to user installation because normal site-packages is not writeable
2022-09-28T11:57:21.2644039Z Collecting docker
2022-09-28T11:57:21.3613073Z   Downloading docker-6.0.0-py3-none-any.whl (147 kB)
2022-09-28T11:57:21.3876113Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.2/147.2 KB 6.6 MB/s eta 0:00:00
2022-09-28T11:57:21.5392196Z Collecting crowdstrike-falconpy
2022-09-28T11:57:21.5475037Z   Downloading crowdstrike_falconpy-1.2.2-py3-none-any.whl (394 kB)
2022-09-28T11:57:21.5862829Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.6/394.6 KB 10.8 MB/s eta 0:00:00
2022-09-28T11:57:21.5960817Z Requirement already satisfied: urllib3>=1.26.0 in /usr/lib/python3/dist-packages (from docker) (1.26.5)
2022-09-28T11:57:21.6324663Z Collecting websocket-client>=0.32.0
2022-09-28T11:57:21.6381679Z   Downloading websocket_client-1.4.1-py3-none-any.whl (55 kB)
2022-09-28T11:57:21.6426988Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.0/55.0 KB 22.5 MB/s eta 0:00:00
2022-09-28T11:57:21.6928060Z Collecting requests>=2.26.0
2022-09-28T11:57:21.6994239Z   Downloading requests-2.28.1-py3-none-any.whl (62 kB)
2022-09-28T11:57:21.7037331Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 18.9 MB/s eta 0:00:00
2022-09-28T11:57:21.7059894Z Requirement already satisfied: packaging>=14.0 in /usr/local/lib/python3.10/dist-packages (from docker) (21.3)
2022-09-28T11:57:21.7159145Z Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=14.0->docker) (2.4.7)
2022-09-28T11:57:21.7225967Z Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.26.0->docker) (2020.6.20)
2022-09-28T11:57:21.7730720Z Collecting charset-normalizer<3,>=2
2022-09-28T11:57:21.7788036Z   Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
2022-09-28T11:57:21.7835801Z Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.26.0->docker) (3.3)
2022-09-28T11:57:21.9875754Z Installing collected packages: websocket-client, charset-normalizer, requests, docker, crowdstrike-falconpy
2022-09-28T11:57:22.3064289Z Successfully installed charset-normalizer-2.1.1 crowdstrike-falconpy-1.2.2 docker-6.0.0 requests-2.28.1 websocket-client-1.4.1
2022-09-28T11:57:22.3916446Z Cloning into 'container-image-scan'...
2022-09-28T11:57:33.4252501Z DEBUG   Trying paths: ['/home/vsts/work/_temp/DockerConfig_1664366208760/config.json', '/home/vsts/.docker/config.json', '/home/vsts/.dockercfg']
2022-09-28T11:57:33.4254068Z DEBUG   Found file at path: /home/vsts/work/_temp/DockerConfig_1664366208760/config.json
2022-09-28T11:57:33.4254931Z DEBUG   Found 'auths' section
2022-09-28T11:57:33.4256097Z DEBUG   Found entry (registry='***', username='***')
2022-09-28T11:57:33.4394826Z DEBUG   http://localhost:None "GET /version HTTP/1.1" 200 907
2022-09-28T11:57:33.4418105Z DEBUG   Starting new HTTPS connection (1): api.eu-1.crowdstrike.com:443
2022-09-28T11:57:34.3193803Z DEBUG   https://api.eu-1.crowdstrike.com:443 "POST /oauth2/token HTTP/1.1" 308 0
2022-09-28T11:57:34.3217562Z DEBUG   Starting new HTTPS connection (1): api.us-2.crowdstrike.com:443
2022-09-28T11:57:35.2197684Z DEBUG   https://api.us-2.crowdstrike.com:443 "POST /oauth2/token HTTP/1.1" 201 1221
2022-09-28T11:57:35.2313146Z DEBUG   http://localhost:None "GET /v1.41/images/json?only_ids=0&all=0&filters=%7B%22reference%22%3A+%5B%22dashbordapi%3ABuild-52958%22%5D%7D HTTP/1.1" 200 3
2022-09-28T11:57:35.2320419Z INFO    Pulling container image: 'dashbordapi:Build-52958'
2022-09-28T11:57:35.2321232Z DEBUG   Looking for auth config
2022-09-28T11:57:35.2322237Z DEBUG   Looking for auth entry for 'docker.io'
2022-09-28T11:57:35.2322717Z DEBUG   No entry found
2022-09-28T11:57:35.2323040Z DEBUG   No auth config found
2022-09-28T11:57:36.6128990Z DEBUG   http://localhost:None "POST /v1.41/images/create?tag=Build-52958&fromImage=dashbordapi HTTP/1.1" 404 174
2022-09-28T11:57:36.6129662Z ERROR   Unknown error
2022-09-28T11:57:36.6130076Z Traceback (most recent call last):
2022-09-28T11:57:36.6130737Z   File "/home/vsts/.local/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
2022-09-28T11:57:36.6131224Z     response.raise_for_status()
2022-09-28T11:57:36.6131821Z   File "/home/vsts/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
2022-09-28T11:57:36.6132337Z     raise HTTPError(http_error_msg, response=self)
2022-09-28T11:57:36.6133136Z requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=Build-52958&fromImage=dashbordapi
2022-09-28T11:57:36.6133549Z 
2022-09-28T11:57:36.6133907Z The above exception was the direct cause of the following exception:
2022-09-28T11:57:36.6134134Z 
2022-09-28T11:57:36.6134409Z Traceback (most recent call last):
2022-09-28T11:57:36.6134953Z   File "/home/vsts/work/1/s/container-image-scan/cs_scanimage.py", line 359, in main
2022-09-28T11:57:36.6135391Z     scan_image.container_tag()
2022-09-28T11:57:36.6135954Z   File "/home/vsts/work/1/s/container-image-scan/cs_scanimage.py", line 82, in container_tag
2022-09-28T11:57:36.6136415Z     self.client.images.pull(local_tag)
2022-09-28T11:57:36.6136997Z   File "/home/vsts/.local/lib/python3.10/site-packages/docker/models/images.py", line 465, in pull
2022-09-28T11:57:36.6137459Z     pull_log = self.client.api.pull(
2022-09-28T11:57:36.6138024Z   File "/home/vsts/.local/lib/python3.10/site-packages/docker/api/image.py", line 429, in pull
2022-09-28T11:57:36.6138482Z     self._raise_for_status(response)
2022-09-28T11:57:36.6139089Z   File "/home/vsts/.local/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
2022-09-28T11:57:36.6139996Z     raise create_api_error_from_http_exception(e) from e
2022-09-28T11:57:36.6140683Z   File "/home/vsts/.local/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
2022-09-28T11:57:36.6141260Z     raise cls(e, response=response, explanation=explanation) from e
2022-09-28T11:57:36.6142493Z docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=Build-52958&fromImage=dashbordapi: Not Found ("pull access denied for dashbordapi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
2022-09-28T11:57:36.6410309Z ##[error]Bash exited with code '10'.
2022-09-28T11:57:36.6442843Z ##[section]Finishing: Scan container-image
```

We ran the docker image command in previous step and can see the image shows as below

```
REPOSITORY                                               TAG           IMAGE ID       CREATED          SIZE
***/dashbordapi                                          Build-52958   549080671830   1 second ago     320MB
```

We did think it was weird that the repo had ***/ which this appears to be the way that Pipelines does it, I have tried specifying ***/ in the image name however that threw more errors

Thes step we have is as follows

```
- task: Docker@2
  displayName: 'Build Docker container'
  inputs:
    command: build
    Dockerfile: 'Dockerfile'
    containerRegistry: 'Azure Container Registry'
    repository: ${{ parameters.imageName }}
    tags: Build-$(Build.BuildId)
- script: |
    docker images --all
    echo $(CONTAINER_REPO)
    echo $(CONTAINER_TAG)
- script: |
    export FALCON_CLIENT_SECRET=$(FALCON_CLIENT_SECRET)
    export FALCON_CLIENT_ID=$(FALCON_CLIENT_ID)
    pip3 install docker crowdstrike-falconpy
    if [ ! -d container-image-scan ] ; then
      git clone https://github.com/crowdstrike/container-image-scan
    fi
    python3 container-image-scan/cs_scanimage.py --log-level DEBUG
  displayName: 'Scan container-image'
```

**Comment by redhatrises** [comment]
This seems to work in the sense that I can build a local dockerfile and scan the image:

```
variables:
- group: cs_falcon_vars
- name: CONTAINER_REPO
  value: 'myimage'
- name: CONTAINER_TAG
  value: $(Build.BuildId)
- name: FALCON_CLOUD_REGION
  value: 'us-1'
#- name: SCORE
#  value: 500

steps:

- task: Docker@2
  inputs:
    repository: $(CONTAINER_REPO)
    tags: $(CONTAINER_TAG)
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build container image'

- script: |
    export FALCON_CLIENT_SECRET=$(FALCON_CLIENT_SECRET)
    export FALCON_CLIENT_ID=$(FALCON_CLIENT_ID)
    pip3 install docker crowdstrike-falconpy
    if [ ! -d container-image-scan ] ; then
      git clone https://github.com/crowdstrike/container-image-scan
    fi
    python3 container-image-scan/cs_scanimage.py
  displayName: 'Scan container-image'
  
- task: Docker@2
  inputs:
    repository: $(CONTAINER_REPO)
    tags: $(CONTAINER_TAG)
    command: 'push'
  displayName: 'Push container image'
```

**Comment by snazy2000** [comment]
Issue resolved, devops was confusing the matter by hiding the azure container registry url with *** soon as added that in to the container_repo variable it all worked :)
